<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, json } from '../api'
const form = reactive<any>({ displaySeconds: 10, animationEnabled: true, animationDuration: 0.8, logoEnabled: true, logoPosition: 'top-left' })
const logo = ref(''), fallback = ref('')
async function load() { const data:any = await api('/config'); form.displaySeconds = data.display_seconds; form.animationEnabled = Boolean(data.animation_enabled); form.animationDuration = Number(data.animation_duration); form.logoEnabled = Boolean(data.logo_enabled); form.logoPosition = data.logo_position; logo.value=data.logo_url||''; fallback.value=data.default_image_url||'' }
onMounted(load)
async function save() { try { await api('/config', json('PUT', form)); ElMessage.success('设置已保存') } catch(e:any) { ElMessage.error(e.message) } }
async function image(event: Event, kind: string) { const file=(event.target as HTMLInputElement).files?.[0]; if(!file) return; const data=new FormData(); data.append('file',file); try { await api(`/config/${kind}`, { method:'POST', body:data }); await load(); ElMessage.success('图片已更新') } catch(e:any) { ElMessage.error(e.message) } }
</script>
<template><div class="page-heading"><div><h1>展示设置</h1><p>大厅页面会定时获取最新设置。</p></div></div><el-card class="settings-card"><el-form label-width="130px"><el-form-item label="每页停留"><el-input-number v-model="form.displaySeconds" :min="1" :max="3600"/> 秒</el-form-item><el-form-item label="切换动画"><el-switch v-model="form.animationEnabled"/></el-form-item><el-form-item label="动画效果"><el-select model-value="fade" disabled><el-option label="淡入淡出" value="fade"/></el-select></el-form-item><el-form-item label="动画时长"><el-input-number v-model="form.animationDuration" :min="0" :max="10" :step="0.1"/> 秒</el-form-item><el-form-item label="显示 Logo"><el-switch v-model="form.logoEnabled"/></el-form-item><el-form-item label="Logo 位置"><el-select v-model="form.logoPosition"><el-option label="左上角" value="top-left"/><el-option label="右上角" value="top-right"/><el-option label="左下角" value="bottom-left"/><el-option label="右下角" value="bottom-right"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="save">保存设置</el-button></el-form-item></el-form></el-card><div class="asset-grid"><el-card><h3>学院 Logo</h3><img v-if="logo" :src="logo" class="asset-preview"><p v-else class="hint">尚未上传 Logo</p><input type="file" accept="image/png,image/jpeg" @change="image($event,'logo')"></el-card><el-card><h3>默认宣传画面</h3><img v-if="fallback" :src="fallback" class="asset-preview"><p v-else class="hint">当前使用系统内置画面</p><input type="file" accept="image/png,image/jpeg" @change="image($event,'default-image')"></el-card></div></template>
